# Generated by Django 5.2.7 on 2025-11-10 14:45

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="العنوان")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="وسوم (CSV)"
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, verbose_name="رابط خارجي (اختياري)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.portfolio_upload,
                        verbose_name="صورة العرض (اختياري)",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.portfolio_upload,
                        verbose_name="ملف (اختياري)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="ظهور عام"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "عنصر معرض أعمال",
                "verbose_name_plural": "عناصر معرض الأعمال",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="avg_response_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="متوسط زمن الاستجابة بالدقائق"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="المدينة"),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="client_satisfaction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="رضا العملاء (0–100)",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="completed_jobs",
            field=models.PositiveIntegerField(default=0, verbose_name="طلبات مكتملة"),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("none", "بدون توثيق"),
                    ("pending", "قيد المراجعة"),
                    ("verified", "موثّق"),
                    ("rejected", "مرفوض"),
                ],
                default="none",
                max_length=20,
                verbose_name="حالة التوثيق",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="kyc_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ توثيق KYC"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="national_id_last4",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="آخر 4 أرقام من الهوية (اختياري)"
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0, verbose_name="عدد التقييمات"),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(fields=["city"], name="profiles_em_city_c9675e_idx"),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(
                fields=["kyc_status"], name="profiles_em_kyc_sta_d252d5_idx"
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioitem",
            index=models.Index(
                fields=["owner", "is_public"], name="profiles_po_owner_i_acd847_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioitem",
            index=models.Index(
                fields=["sort_order"], name="profiles_po_sort_or_c960c8_idx"
            ),
        ),
    ]
