# Generated by Django 5.1.2 on 2025-11-11 13:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0002_portfolioitem_employeeprofile_avg_response_minutes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="سعر الساعة (اختياري)",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="skills",
            field=models.CharField(
                blank=True,
                help_text="اكتب المهارات مفصولة بفواصل: Django, REST, Tailwind",
                max_length=400,
                verbose_name="مهارات (CSV)",
            ),
        ),
    ]
