# Generated by Django 5.1.2 on 2025-11-11 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disputes", "0001_initial"),
        ("marketplace", "0008_delete_servicerequest_note_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispute",
            options={
                "ordering": ["-opened_at"],
                "verbose_name": "نزاع",
                "verbose_name_plural": "نزاعات",
            },
        ),
        migrations.RemoveConstraint(
            model_name="dispute",
            name="uniq_open_dispute_per_request",
        ),
        migrations.AlterField(
            model_name="dispute",
            name="details",
            field=models.TextField(blank=True, verbose_name="تفاصيل"),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="milestone_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="مرحلة مرتبطة (ID)"
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="opened_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ الفتح"
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="opened_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opened_disputes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="فُتح بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="opener_role",
            field=models.CharField(
                choices=[("client", "عميل"), ("employee", "موظف"), ("admin", "إداري")],
                max_length=16,
                verbose_name="دور مُنشئ النزاع",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="reason",
            field=models.TextField(verbose_name="السبب"),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="marketplace.request",
                verbose_name="الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحسم"
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_disputes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُل بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="resolved_note",
            field=models.TextField(blank=True, verbose_name="ملاحظة الحسم"),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "مفتوح"),
                    ("in_review", "قيد المراجعة"),
                    ("resolved", "محسوم"),
                    ("canceled", "ملغى"),
                ],
                default="open",
                max_length=16,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="title",
            field=models.CharField(max_length=200, verbose_name="العنوان"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["request", "status"], name="disputes_di_request_49beae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["opened_at"], name="disputes_di_opened__6bcf3f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["open", "in_review"])),
                fields=("request",),
                name="uniq_open_or_review_dispute_per_request",
            ),
        ),
    ]
