# Generated by Django 5.2.7 on 2025-11-11 09:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0007_alter_agreement_total_amount_and_more"),
        ("finance", "0002_invoice_due_at_alter_invoice_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="platform_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="قيمة عمولة المنصّة",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="platform_fee_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.10"),
                help_text="مثال: 0.10 = 10٪. تُحتسب على P.",
                max_digits=5,
                verbose_name="نسبة المنصّة",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="P + عمولة المنصّة",
                max_digits=12,
                verbose_name="المجموع الفرعي",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ النهائي الذي يراه العميل ويدفعه",
                max_digits=12,
                verbose_name="الإجمالي المستحق",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="قيمة الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.15"),
                help_text="مثال: 0.15 = 15٪. تُحتسب على (P + عمولة المنصّة).",
                max_digits=5,
                verbose_name="نسبة الضريبة VAT",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="المبلغ (P)",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                help_text="يُفضّل فاتورة واحدة لكل مرحلة.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="agreements.milestone",
                verbose_name="الدفعة/المرحلة",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="ref_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="مرجع الدفع من بوابة/حوالة (قد لا يكون فريدًا).",
                max_length=100,
                verbose_name="مرجع العملية",
            ),
        ),
    ]
