# Generated by Django 5.2.7 on 2025-11-12 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0009_alter_milestone_amount"),
        ("finance", "0003_invoice_platform_fee_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid_ref",
            field=models.CharField(
                blank=True,
                help_text="رقم/مرجع التحويل البنكي الذي يرسله العميل أو تسجله المالية بعد المراجعة.",
                max_length=64,
                null=True,
                verbose_name="مرجع الدفع البنكي",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["paid_ref"], name="finance_inv_paid_re_63d838_idx"
            ),
        ),
    ]
