# Generated by Django 5.2.7 on 2025-11-12 16:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0009_alter_milestone_amount"),
        ("finance", "0004_invoice_paid_ref_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_fee_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.10"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="نسبة عمولة المنصّة (0..1)",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.15"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="نسبة VAT (0..1)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="المبلغ المصروف للموظف",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("paid", "مدفوع"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="طريقة الصرف",
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="مرجع العملية",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="ملاحظة"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ الإنشاء",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="تاريخ الصرف"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payouts",
                        to="agreements.agreement",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payouts",
                        to="finance.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "أمر صرف",
                "verbose_name_plural": "أوامر الصرف",
                "ordering": ["-issued_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "issued_at"],
                        name="finance_pay_status_9a84eb_idx",
                    ),
                    models.Index(
                        fields=["employee", "status"],
                        name="finance_pay_employe_daab10_idx",
                    ),
                ],
            },
        ),
    ]
