# Generated by Django 5.2.7 on 2025-11-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_financesettings_payout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financesettings",
            options={
                "verbose_name": "إعدادات مالية",
                "verbose_name_plural": "إعدادات مالية",
            },
        ),
    ]
