# Generated by Django 5.2.7 on 2025-11-21 11:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_financesettings_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="platform_fee_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.00"),
                help_text="تم تعطيل الحسابات التلقائية.",
                max_digits=5,
                verbose_name="نسبة المنصّة",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="تم تعطيل الحسابات التلقائية.",
                max_digits=12,
                verbose_name="المجموع الفرعي",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ النهائي الذي يراه العميل ويدفعه (المبلغ المدخل فقط)",
                max_digits=12,
                verbose_name="الإجمالي المستحق",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="vat_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.00"),
                help_text="تم تعطيل الحسابات التلقائية.",
                max_digits=5,
                verbose_name="نسبة الضريبة VAT",
            ),
        ),
    ]
