# Generated by Django 5.1.2 on 2025-11-21 12:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0011_alter_milestone_amount"),
        ("finance", "0007_alter_invoice_platform_fee_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="paid_ref",
            field=models.CharField(
                blank=True,
                help_text="مرجع التحويل البنكي الذي يرسله العميل.",
                max_length=64,
                null=True,
                verbose_name="مرجع الدفع البنكي",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="platform_fee_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.00"),
                help_text="تم تعطيل الحسابات التلقائية داخل Invoice.",
                max_digits=5,
                verbose_name="نسبة المنصّة",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "غير مدفوعة"),
                    ("paid", "مدفوعة"),
                    ("cancelled", "ملغاة"),
                ],
                db_index=True,
                default="unpaid",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="عرض افتراضي فقط.",
                max_digits=12,
                verbose_name="المجموع الفرعي",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ النهائي الذي يراه العميل ويدفعه (افتراضيًا = amount).",
                max_digits=12,
                verbose_name="الإجمالي المستحق",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="vat_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.00"),
                help_text="تم تعطيل الحسابات التلقائية داخل Invoice.",
                max_digits=5,
                verbose_name="نسبة الضريبة VAT",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payouts",
                to="agreements.agreement",
                verbose_name="الاتفاقية",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payouts",
                to="finance.invoice",
                verbose_name="الفاتورة",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("paid", "مدفوع"),
                    ("cancelled", "ملغي"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TaxRemittance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="إجمالي الضريبة المُورَّدة في هذه العملية.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="مبلغ التوريد",
                    ),
                ),
                (
                    "period_from",
                    models.DateField(blank=True, null=True, verbose_name="من تاريخ"),
                ),
                (
                    "period_to",
                    models.DateField(blank=True, null=True, verbose_name="إلى تاريخ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("sent", "تم التوريد"),
                            ("cancelled", "ملغي"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="رقم مرجع السداد/التحويل للضريبة.",
                        max_length=100,
                        verbose_name="مرجع التوريد",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="ملاحظة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاريخ التوريد",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "توريد ضريبة",
                "verbose_name_plural": "توريدات الضريبة",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="finance_tax_status_316b8d_idx",
                    ),
                    models.Index(
                        fields=["period_from", "period_to"],
                        name="finance_tax_period__d29dbf_idx",
                    ),
                ],
            },
        ),
    ]
