# Generated by Django 5.2.7 on 2025-11-21 13:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_invoice_paid_ref_and_more"),
        ("marketplace", "0009_offer_client_total_amount_cache"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="المبلغ المرجع",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="سبب الإرجاع")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار التنفيذ"),
                            ("sent", "تم الإرجاع"),
                            ("failed", "فشل الإرجاع"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="طريقة الإرجاع"
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مرجع الإرجاع"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإرجاع"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="finance.invoice",
                        verbose_name="الفاتورة",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="marketplace.request",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرتجع عميل",
                "verbose_name_plural": "مرتجعات العملاء",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
