# Generated by Django 5.2.7 on 2025-11-22 07:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_refund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="platform_fee_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.00"),
                help_text="تُخصم من الموظف فقط.",
                max_digits=5,
                verbose_name="نسبة المنصّة (0..1)",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="يساوي P للعرض.",
                max_digits=12,
                verbose_name="المجموع الفرعي (P)",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="= P + ضريبة P.",
                max_digits=12,
                verbose_name="الإجمالي المستحق من العميل",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="vat_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.00"),
                help_text="ضريبة على السعر المقترح فقط.",
                max_digits=5,
                verbose_name="نسبة الضريبة VAT (0..1)",
            ),
        ),
    ]
