# Generated by Django 5.2.7 on 2025-12-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_alter_ledgerentry_options_alter_invoice_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                help_text="صورة إيصال التحويل البنكي.",
                null=True,
                upload_to="receipts/%Y/%m/",
                verbose_name="صورة الإيصال",
            ),
        ),
    ]
