# Generated by Django 5.2.7 on 2025-11-02 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_alter_request_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="request",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_duration_days__gt", 0)),
                name="request_duration_days_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="request",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_price__gte", 0)),
                name="request_estimated_price_gte_0",
            ),
        ),
    ]
