# Generated by Django 5.2.7 on 2025-11-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_request_request_duration_days_gt_0_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="offer_selected_at",
        ),
        migrations.AddField(
            model_name="request",
            name="selected_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
