# Generated by Django 5.1.2 on 2025-11-10 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_remove_request_offer_selected_at_request_selected_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="request",
            name="offers_window_ends_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="نهاية نافذة استقبال العروض (5 أيام)",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="proposed_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="request",
            name="agreement_due_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="موعد استحقاق إرسال الاتفاقية (SL A 3 أيام)",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="selected_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="وقت اختيار العرض (للحالة OFFER_SELECTED وما بعدها)",
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["offers_window_ends_at"], name="marketplace_offers__991db3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "withdrawn"), _negated=True),
                fields=("request", "employee"),
                name="uq_active_offer_per_employee_per_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(
                condition=models.Q(("proposed_duration_days__gt", 0)),
                name="offer_duration_days_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(
                condition=models.Q(("proposed_price__gte", 0)), name="offer_price_gte_0"
            ),
        ),
    ]
