# Generated by Django 5.2.7 on 2025-11-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_servicerequest_request_offers_window_ends_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServiceRequest",
        ),
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="agreement_due_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="موعد استحقاق إرسال الاتفاقية (SLA 3 أيام)",
            ),
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "طلبات",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("marketplace.request",),
        ),
    ]
