# Generated by Django 5.2.7 on 2025-11-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_email_user_uniq_user_email_ci"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined", "id"],
                "verbose_name": "مستخدم",
                "verbose_name_plural": "مستخدمون",
            },
        ),
    ]
