# Generated by Django 5.2.7 on 2025-11-11 08:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0006_agreement_agreement_total_amount_gte_0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="قيمة المشروع P (ريال)",
            ),
        ),
        migrations.AlterField(
            model_name="agreementclause",
            name="key",
            field=models.SlugField(
                help_text="معرّف (إنجليزي) للبند",
                unique=True,
                verbose_name="المعرّف الفريد",
            ),
        ),
    ]
