# Generated by Django 5.2.7 on 2025-11-11 19:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0007_alter_agreement_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="المبلغ (ريال)",
            ),
        ),
    ]
