# Generated by Django 5.2.7 on 2025-11-11 19:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0008_alter_milestone_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="المبلغ (ريال)",
            ),
        ),
    ]
