# Generated by Django 5.2.7 on 2025-11-14 11:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0009_alter_milestone_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="milestone",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "مرحلة",
                "verbose_name_plural": "مراحل",
            },
        ),
        migrations.AddField(
            model_name="agreement",
            name="started_at",
            field=models.DateField(
                blank=True,
                help_text="يُضبط تلقائيًا عند تأكيد دفع الاتفاقية من المالية.",
                null=True,
                verbose_name="تاريخ بداية التنفيذ",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="يُستخدم فقط عند تفعيل ربط المراحل بالدفعات مستقبلاً، حاليًا يبقى صفرًا.",
                max_digits=12,
                verbose_name="المبلغ (ريال)",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="due_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="مثال: 10 أيام للتسليم الأولي. مجموع مدد المراحل لا يتجاوز مدة المشروع المتفق عليها.",
                null=True,
                verbose_name="مدة المرحلة (أيام)",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="title",
            field=models.CharField(max_length=160, verbose_name="عنوان المرحلة"),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_days__isnull", True), ("due_days__gte", 1), _connector="OR"
                ),
                name="milestone_due_days_gte_1_or_null",
            ),
        ),
    ]
