# Generated by Django 5.2.7 on 2025-11-14 11:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0010_alter_milestone_options_agreement_started_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="لا تُستخدم هذه القيمة في الفواتير حاليًا، حقل احتياطي فقط.",
                max_digits=12,
                verbose_name="المبلغ (ريال)",
            ),
        ),
    ]
