# Generated by Django 5.1.2 on 2025-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0012_agreement_extension_requested_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="modification_reason",
            field=models.TextField(blank=True, verbose_name="سبب تعديل المبلغ"),
        ),
        migrations.AddField(
            model_name="agreement",
            name="modification_requested_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="المبلغ الإجمالي الجديد المقترح للاتفاقية.",
                max_digits=12,
                null=True,
                verbose_name="المبلغ الجديد المطلوب (ريال)",
            ),
        ),
    ]
